const mongoose=require('mongoose');
const postSchema= new mongoose.Schema({
    caption:String,
    image:{
        public_id:String,
        url:String
    },
owner:{
    type:mongoose.Schema.Types.ObjectId,
    ref:"user",
},
createdAt:{
    type:Date,
    default:Date.now,
},
likes:[
    {
        user:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"user"
        },
    }
],
Comments:[{
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user"
    },
    comment:{
        type:String,
        required:true,
    }
}]
});
module.exports=mongoose.model("Post",postSchema);